# Generated by Django 4.2.11 on 2025-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='293a0215', max_length=10, unique=True),
        ),
    ]
