# Generated by Django 4.2.11 on 2025-07-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0006_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='c9938ff1', max_length=10, unique=True),
        ),
    ]
