# Generated by Django 4.2.11 on 2025-07-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0007_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='3b0645f4', max_length=10, unique=True),
        ),
    ]
