# Generated by Django 4.2.11 on 2025-07-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0010_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='8c9577be', max_length=10, unique=True),
        ),
    ]
