# Generated by Django 4.2.11 on 2025-07-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0013_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='e52903d3', max_length=10, unique=True),
        ),
    ]
