# Generated by Django 4.2.11 on 2025-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0022_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='0d7095a5', max_length=10, unique=True),
        ),
    ]
